-- AlterTable
ALTER TABLE `peminjaman` MODIFY `status_peminjaman` ENUM('PENGAJUAN', 'MENUNGGU_PEMBAYARAN', 'MENUNGGU_PERSETUJUAN', 'DISETUJUI', 'DITOLAK', 'SELESAI', 'DIBATALKAN') NOT NULL DEFAULT 'PENGAJUAN';
